apiVersion: v1
kind: Pod
metadata:
  name: elk
spec:
  containers:
    - name: elk
      image: sebp/elk:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 5601
      - containerPort: 9200
      - containerPort: 5044